### ISSUE TITLE
Running sinatra app with rackup

### ISSUE THREAD

**Issue by ddnexus** [ruby/vscode-rdbg#10]
I have a simple sinatra app that runs on puma with rackup that I wanted to try to debug. I runs with:

`rackup -o 0.0.0.0 -p 4567 /path/to/app.ru`

If paste that in the prompt, it starts the debug, but it stops inside puma (or webrick when I tried to run it). Everything inside the backtrace says "RUNNING"  but nothing happens.

How should I debug it?

**Comment by ko1** [comment]
Sorry I can't understand the situation. Could you give us your repro process and code?

**Comment by ddnexus** [comment]
Sure.
You can use this [self-contained app](https://github.com/ddnexus/pagy/blob/master/apps/pagy_standalone_app.ru).

Just switch comments in lines 30-31 so you don't have to clone the whole repo.

Put a breakpoint at line 63, and access the app at `http://0.0.0.0:8080` and you should see what I mean.

**Comment by ko1** [comment]
Thank you, I can reproduce the issue.
I'll try to check.
