### ISSUE TITLE
On Mac Os, Unable to use my installed ruby, vs code always picks the system one

### ISSUE THREAD

**Issue by cheradenine** [ruby/vscode-rdbg#13]
On Mac OS
I have installed ruby 3.0.2
When I run in my shell and run
`which ruby`
I get 3.0.2 and when I run
`ruby --version` I get`ruby 3.0.2p107 (2021-07-07) [arm64-darwin20]`

I launch vs code via the code command line from this shell. If I go into Vs terminal and type the above commands I get the same output.

When I try to debug a .rb file I do not see the debug dialog and instead VS code tries to run the system installed ruby version (2.6.0) and fails:

```
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/dependency.rb:313:in `to_specs': Could not find 'io-console' (~> 0.5) - did find: [io-console-0.4.7] (Gem::MissingSpecVersionError)
Checked in 'GEM_PATH=/Users/me/work/gems', execute `gem env` for more information
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1449:in `block in activate_dependencies'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1438:in `each'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.

```
I also did try making a launch file and explicitly setting 'askParameters': true but I still never get the debug dialog, just this output.

**Comment by ko1** [comment]
Thank you for your report.

(1) do you use `rbenv`?
(2) what did you do on VSCode?
(2-1) DId you write .vscode/launch.json?
(2-2) Which menu did you select?
(3) Do you have output log? There are two logs: (1) rdbg terminal and (2) rdbg output.

Terminal:
![image](https://user-images.githubusercontent.com/9558/142100898-a427af40-c902-43cb-af4b-b555bc713713.png)

Output log:
![image](https://user-images.githubusercontent.com/9558/142101087-f4631f05-dde0-423d-a31f-0bec4b78f141.png)

**Comment by cheradenine** [comment]
I should add that the extension worked at some point and then stopped and I'm not aware of any config changes that I had made. When it did work, if I clicked 'Run and Debug' I would get the debug dialog and I could just type 'Rails server' and it worked beautifully! I must have messed up my vscode config somewhere but no idea how or where.

1. I am using nix for environment management. It works by altering my path
2. I clicked on 'Run and Debug' in the debug tab (with no launch.json)
2-1. I tried creating a launch.json
2-2. I didn't use a menu, or if you mean the drop down w/ launch.json I selected launch (not attach)
3. rdbg fails to run because vscode is using the wrong ruby - it finds the gem in my environment using the path I expect from my GEM_PATH as configured in my shell. There is no output in the terminal from trying to run it, and the rdbg output is what I see in the first post above.

Some people have suggested that launching vscode from within my shell with the environment activated should work, and it seems like GEM_PATH is correct when launching vscode this way, and not correct if I run it via the mac os launcher. But the path to ruby is wrong.
I don't have any other logs - never get that far because rdbg doesn't run.

I may try uninstalled vscode and starting from a fresh install. No idea if that would help.

**Comment by ko1** [comment]
Do you choose (open) `*.rb` file when you click "Run and Debug" button?
If it is not, vscode-rdbg will not run.

**Comment by cheradenine** [comment]
I'm pretty sure this is something to do with my environment and not a bug in rdbg. It must just be something about how vscode + ruby are conspiring against me to avoid doing my bidding.

I have a .rb file open. When I click 'Run and Debug' I get no dialog. I was poking around and it looks like, from the call stack that rdbg is loading rubygems from the system install and not my dev environment. It is something goofy with vscode because in my terminal or the terminal from within vscode the paths, gem env all look correct to me. The rdbg script shebang when run in my vscode terminal:

```
> /usr/bin/env ruby --version
ruby 3.0.2p107 (2021-07-07) [arm64-darwin20]

```
Full output (only output I can find) from the Output tab:
```
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/dependency.rb:313:in `to_specs': Could not find 'io-console' (~> 0.5) - did find: [io-console-0.4.7] (Gem::MissingSpecVersionError)
Checked in 'GEM_PATH=/Users/johnb/work/my-project/.nix-gems', execute `gem env` for more information
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1449:in `block in activate_dependencies'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1438:in `each'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1438:in `activate_dependencies'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1420:in `activate'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1452:in `block in activate_dependencies'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1438:in `each'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1438:in `activate_dependencies'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1420:in `activate'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1452:in `block in activate_dependencies'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1438:in `each'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1438:in `activate_dependencies'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1420:in `activate'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:304:in `block in activate_bin_path'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:303:in `synchronize'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:303:in `activate_bin_path'
	from /Users/johnb/work/my-project/.nix-gems/bin/rdbg:25:in `<main>'

Error: exit code is 1
Make sure to install rdbg command (`gem install debug`).
If you are using bundler, write `gem 'debug'` in your Gemfile.
[Start session]
{"_debugServiceProxy":{},"_id":"8dd1a92b-8211-465c-ac77-c06c7fbbc0ae","_type":"rdbg","_name":"Launch","_workspaceFolder":{"uri":{"$mid":1,"fsPath":"/Users/johnb/work/my-project","external":"file:///Users/johnb/work/my-project","path":"/Users/johnb/work/my-project","scheme":"file"},"name":"my-project","index":0},"_configuration":{"type":"rdbg","name":"Launch","request":"launch","script":"/Users/johnb/work/my-project/app/models/color.rb","askParameters":true}}

```

**Comment by cheradenine** [comment]
Some new info after trying things. It took me a while but I proved to myself that vs code was not using any of the environment variables from my shell even when launching it via the `code` cli.
I read this page:
https://code.visualstudio.com/docs/python/environments#_environment-variable-definitions-file
And tried creating a .env file in my workspace and I got a lot further. I'm getting the debug dialog, and the right ruby, rdbg, etc. Amazing.
But now the debug module initialization is failing:

```
/Users/johnb/work/my-app/vendor/cache/ruby/3.0.0/gems/debug-1.3.4/lib/debug/config.rb:60:in `initialize': Can not make multiple configurations in one process (RuntimeError)
```

Is this diagnosable or any suggestions to try? I was so happy to see vscode light up orange ready to debug. It is such an incredible tool and experience when it is working.

**Comment by iandol** [comment]
I also had a regression where VSCode couldn't find the correct Ruby (also on macOS Monterey, using rbenv). I solved it by specifying the path to `rdbg` specifically:

```json
{ // Name: VSCode rdbg Ruby Debugger https://marketplace.visualstudio.com/items?itemName=KoichiSasada.vscode-rdbg
	"type": "rdbg",
	"name": "Attach with Ruby Debug rdbg",
	"request": "attach",
	"rdbgPath": "~/.rbenv/shims/rdbg"
}
```

**Comment by ko1** [comment]
> And tried creating a .env file in my workspace and I got a lot further. I'm getting the debug dialog, and the right ruby, rdbg, etc. Amazing.

Ah, I see. So it is not an issue of rdbg, but the issue with vscode and nix (I don't know this tool tough).

>  initialize': Can not make multiple configurations in one process (RuntimeError)
> Is this diagnosable or any suggestions to try? I was so happy to see vscode light up orange ready to debug. It is such an incredible tool and experience when it is working.

This error is raised because multiple configuration are tried to create.
Could you try with very small script, like `p :hello` in `t.rb` and kick the script?

**Comment by HLFH** [comment]
On my side, I had the same issue with chruby. And I added: "rdbgPath": "~/.gem/ruby/3.1.1/bin/rdbg"
Might be good to precise rdbgPath is recommended in the README if using chruby, nix, or rbenv.
And you might close as well https://github.com/ruby/vscode-rdbg/issues/13 and https://github.com/ruby/vscode-rdbg/issues/21.

**Comment by ko1** [comment]
I see. It can be a good idea.

**Comment by ko1** [comment]
d28305bfc26b470e298336811c031fcd854194cf

**Comment by ko1** [comment]
I'll debug if someone can provide repro scenario, and please reopen the issue (or make another issue or PR).
Thank you.

**Comment by arizz96** [comment]
I ran into the same issue and got it working. When using `zsh`, it appears that `.zshrc` file is not directly loaded in login shells (more on that [here](https://apple.stackexchange.com/a/432227)).
I debugged the initialisation process of the debugger extension, and the error comes from:
https://github.com/ruby/vscode-rdbg/blob/9d445b9804e7c2084e7524ae9ae76e5787a4c2b1/src/extension.ts#L332

In that particular point, the command `/bin/zsh -l -c 'bundle exec rdbg --util=gen-sockpath'` is being executed and it fails showing an error that reports the usage of _system_ Ruby installation.

So I tried running a simple `/bin/zsh -l -c 'which bundle'` and the result was `/usr/bin/bundle`, which is not what I was expecting for. Adding a `-d` (`--no-globalrcs`) would have solved, but it would require extension changes.

As a consequence `$PATH` in that shell doesn't properly contain rbenv shims (checkable with `/bin/zsh -l -c 'echo $PATH'`).

The solution for me was adding `eval "$(rbenv init -)"` to the `.zprofile` file. As an alternative, adding `export PATH="$HOME/.rbenv/bin:$PATH"` works as well.

**Comment by ko1** [comment]
> The solution for me was adding eval "$(rbenv init -)" to the .zprofile file. As an alternative, adding export PATH="$HOME/.rbenv/bin:$PATH" works as well.

Thank you for the debugging. I'm not an expert of zsh, but your solution is enough or should we support something for zsh on this extension?

**Comment by arizz96** [comment]
> Thank you for the debugging. I'm not an expert of zsh, but your solution is enough or should we support something for zsh on this extension?

Not sure of it, it's the first time I got this issue with `zsh`, maybe it's because it's not so common to do a login in via `-l` in a shell when you're already logged in there. But again, not sure of it.

**Comment by bdewater** [comment]
It might be of interest to see how Shopify's Ruby LSP plugin solved loading chruby: https://github.com/Shopify/vscode-ruby-lsp/pull/226

**Comment by ko1** [comment]
Re-reading https://github.com/ruby/vscode-rdbg/issues/13#issuecomment-1249316284 (and man) I understand that 

* `~/.zshrc` is only loaded for interactive shell
* `zsh -l -c ...` doesn't load `~/.zshrc` but VSCode extension needs to load it. Because `zsh -l` doesn't run interactive shell.
* https://github.com/rbenv/rbenv writes that `>> ~/.zshrc`.

I think `zprofile` seems better place to put configuration as @arizz96 had wrote.

**Comment by ko1** [comment]
... if `rbenv` don't want to restrict the usage only on the interactive shell.

**Comment by ono-max** [comment]
https://github.com/ruby/vscode-rdbg/pull/124 Fixes this issue.
