### ISSUE TITLE
Cannot remove breakpoint while debugging

### ISSUE THREAD

**Issue by jljse** [ruby/vscode-rdbg#17]
## Environment
- Windows11 WSL2: ubuntu 20.04.1
- ruby: 3.1.0p0 (in rbenv in wsl2)
- debug gem: 1.4.0 (globaly installed)
- vscode: 1.63.2
- vscode Remote - WSL: v0.63.13
- vscode rdbg ruby debugger: v0.0.8

## What happened
I cannot remove breakpoint from vscode.
It looks removed on GUI, but keeps breaking.

## Reproduce
1. Make foo.rb
```
3.times do
  puts "hello"
end
```

2. Set breakpoint with vscode on puts line.
3. Run debug with default setting (Debug current file with rdbg)
4. (Breaks on puts line)
5. Remove breakpoint and press F5
6. (breaks on puts line again)

**Comment by ko1** [comment]
Thank you. This issue is on my list.
I'll fix it soon.
