### ISSUE TITLE
windows error on permissions

### ISSUE THREAD

**Issue by dsisnero** [ruby/vscode-rdbg#18]
F:/windows/tools/ruby/Ruby30-x64/lib/ruby/gems/3.0.0/gems/debug-1.4.0/lib/debug/config.rb:384:in `check_dir_authority': C:/Users/DOMINI~1/AppData/Local/Temp/ruby-debug-sock-0's mode is 40755 (should be 040700) (RuntimeError)

**Comment by ko1** [comment]
BTW which ruby distribution do you use?

**Comment by ko1** [comment]
on my ruby -v
> ruby 3.2.0dev (2022-01-14T04:46:12Z gh-4636 c613d79f9b) [x64-mswin64_140]

I want to know `[x64-mswin64_140]` part.

**Comment by jabamaus** [comment]
I beg your pardon :)

ruby 3.1.0p0 (2021-12-25 revision fb4df44d16) [x64-mingw-ucrt]

This is just a pre-built ruby installer I downloaded.

**Comment by ko1** [comment]
Could you trye TCP/IP with `debugPort` option?
Named pipe is not supported on Windows.
https://github.com/ruby/vscode-rdbg/pull/25

**Comment by ruehsn** [comment]
I am having similar issue with VS code and Windows.

I've updated my launch.json config to:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "rdbg",
            "name": "Debug current file with rdbg",
            "request": "launch",
            "script": "${file}",
            "args": [],
            "askParameters": true,
            "debugPort": "12345"
        },
        {
            "type": "rdbg",
            "name": "Attach with rdbg",
            "request": "attach",
            "debugPort": "12345"
        }
    ]
}
```
but then get this error message: Connection ECONNREFUSED 127.0.0.1:12345
![image](https://user-images.githubusercontent.com/5944110/160025965-b23297cf-a33b-4a54-8fd8-18f3d2f36790.png)

I think I misssed a step...

**Comment by ko1** [comment]
#25 is not released yet.
