### ISSUE TITLE
Please push latest version (0.0.8 or later)

### ISSUE THREAD

**Issue by vmi** [ruby/vscode-rdbg#19]
The marketplace version is 0.0.8, but the repository version looks like 0.0.7.
Would you please push the latest version?

**Comment by jabamaus** [comment]
The market place version is still newer than this repo.... Would be good to sync.

**Comment by hsbt** [comment]
@ko1 Do you have a newer version on your box?

**Comment by ko1** [comment]
Sorry I uploaded.
