### ISSUE TITLE
Add (choose) a license

### ISSUE THREAD

**Issue by orgcontrib** [ruby/vscode-rdbg#202]
[Coose a license](https://choosealicense.com). Please add a LICENSE.md to the repo.
MIT would be a no brainer given the acknowledgement.

**Comment by kswartz26** [comment]
This is fairly important: organizations that choose to use this software in a product are technically unable to comply with the terms of the license, because the MIT license specifically requires that a copy of the license be provided when distributing.  Can this please be addressed?

**Comment by ono-max** [comment]
https://github.com/ruby/vscode-rdbg/commit/27963ffa27bbd283e322fe478bbd4953b576aece
