### ISSUE TITLE
Use the Debug Console

### ISSUE THREAD

**Issue by vovimayhem** [ruby/vscode-rdbg#22]
Currently, the extension launches a terminal process whenever a launch configuratin gets launched.

However, a better option would be to let the launched process be visible - and allow to interact with - in the [Debug Console REPL](https://code.visualstudio.com/docs/editor/debugging#_debug-console-repl), similar to how [Rebornix's Ruby Extension](https://marketplace.visualstudio.com/items?itemName=rebornix.Ruby) does.

**Comment by ko1** [comment]
You can interact with debug console by choosing a tab.
The disadvantage of using debug console primary is, we can not input to STDIN.

Do you want to make an option to use only debug console (and give up STDIN)?

**Comment by jabamaus** [comment]
+1 for this! I would give up STDIN like a shot if I could have my terminal back :)

**Comment by ko1** [comment]
Let me clear.
Now it supports "debug console" by choosing the tab.
Do you want to request further?

**Comment by jabamaus** [comment]
What I want is the output from rdbg to go to the debug console no matter which tab is selected. I want the terminal to always remain untouched. Personally I'm not fussed about STDIN in the debug console.

**Comment by ko1** [comment]
could you clear what is "output from rdbg"?

**Comment by jabamaus** [comment]
I mean the launching of the rdbg command and its output. I want that in the debug console instead of the terminal :)

![image](https://user-images.githubusercontent.com/49597106/164617785-997b5462-9360-458d-9816-4f2d9bd123fb.png)

**Comment by jabamaus** [comment]
Do you think you will be able to stop rdbg taking over the terminal? It's really annoying!

**Comment by ko1** [comment]
Ah, so you want:

* 1. Do not show terminal (rdbg invocation and messages).
* 2. All output should be printed on "OUTPUT" tab.
* 3. And you don't want to use STDIN anymore for debuggee.

Does it correct?

Again, I'm worry about (3).

**Comment by jabamaus** [comment]
I'm personally not bothered about 3 at all but it sounds like it could be possible anyway based on what the original poster said. There might be some code to look at in the link he posted.

**Comment by ko1** [comment]
Yes, introducing other options is possible.

**Comment by rockorequin** [comment]
Isn't this now supported in 0.1.0? By default vscode-rdbg now sends output to the debug console and you need to specify useTerminal: true in the launch.json to send output to a terminal. Or have I misunderstood what the enhancement request is for?

**Comment by jabamaus** [comment]
I've just tried the launch option again and it no longer steals the terminal so my problem is solved. Thank you very much :)

**Comment by ko1** [comment]
Great! Sorry I forget to tell you.

**Comment by vovimayhem** [comment]
I forgot about this a long time ago - I guess I was under a lot of stuff... belated thanks @ko1 !
