### ISSUE TITLE
ArgumentError: too long unix socket path (X bytes given but 104 bytes max)

### ISSUE THREAD

**Issue by gorodulin** [ruby/vscode-rdbg#23]
Hi,

I'm getting this error

```text
ruby-3.0.3/lib/ruby/3.0.0/socket.rb:1116:in `unix': too long unix socket path (110 bytes given but 104 bytes max) (ArgumentError)
```
I see in terminal that VS Code tries to execute this command:

```bash
$ rdbg --command --open --stop-at-load --sock-path=/var/folders/hx/bfn57mjd46101yssr0hpxk5r3ndtmm/T/ruby-debug-sock-123136660/ruby-debug-vladimir.gorodulin-35157 -- bundle exec rspec ...
```

Is there a way to make `--sock-path` value shorter by editing `launch.json`?

Details:
- MacOS 11.6.2
- VS Code 1.64.2
- VSCode rdbg Ruby Debugger 0.0.8

Thank you!

**Comment by ko1** [comment]
wow I see.

> Is there a way to make --sock-path value shorter by editing launch.json?

Not yet. I'll make it.

**Comment by ko1** [comment]
https://github.com/ruby/vscode-rdbg/pull/25
Please try `debugPort` option and reopen if you feel inconvinience.
