### ISSUE TITLE
Using debugPort with a socket path does not seem to work with a relative path.

### ISSUE THREAD

**Issue by louim** [ruby/vscode-rdbg#258]
Hello, this issue is related to https://github.com/ruby/debug/issues/982.

Since the autogenerated socket name was too long, I decided to use a local socket path:
```
{
    "type": "rdbg",
    "name": "Attach with rdbg",
    "request": "attach",
    "debugPort": "tmp/rdbg.sock",
}
```
However with this in conjunction with `RUBY_DEBUG_OPEN=true RUBY_DEBUG_SOCK_PATH=tmp/rdbg.sock rails s`, I'm always the following error when trying to Attach to the started process.
![Screenshot 2023-05-19 at 7 31 22 PM](https://github.com/ruby/vscode-rdbg/assets/923718/5731eec9-17eb-4f8d-b621-90f6bd539d02)

I would have expected the config to look up the file relative to the workspace root directory? Using an absolute path to the same folder works: `"debugPort": "/Users/louis-michel.couture/work/my_project/tmp/rdbg.sock",`.

I also tried:
- `"debugPort": "./tmp/rdbg.sock",`
- `"debugPort": "../tmp/rdbg.sock",` thinking it was maybe relative to the launch.json location.
But both of those didn't work.

**Comment by ono-max** [comment]
@louim 
Although we support a relative path in the socket path, you can write as follows:

```
"debugPort": "${workspaceFolder}/foo.sock"
```

**Comment by louim** [comment]
@ono-max thanks!
