### ISSUE TITLE
localfsMap not working

### ISSUE THREAD

**Issue by ghouston** [ruby/vscode-rdbg#290]
I'm attaching to a remote rdbg which i running in the cloud.  I know rdbg works because I can use it from the command-line with `rdbg -A 9876`.  When attaching in vscode, it attaches and stops on `binding.break` as expected.  However, when vscode tries to show the file it is trying to open the path on the server, not the path to the file on my machine where I normally edit the file.  (My local files are synced to the cloud as I make edits).

For example, if I set a `binding.break` in the file `blog_controller.rb` which is located on my machine at `${workspaceFolder}/app/controllers/blog_controller.rb` and on the remote at `/app/app/controllers/blog_controller.rb`.  Then when I attach in vscode and exercise that code, it will hit the binding.break and vscode tries to open `/app/app/controllers/blog_controller.rb` which doesn't exist on my local.  Instead I expected it to open `${workspaceFolder}/app/controllers/blog_controller.rb` which on mac os is `/Users/<my user>/work/blog/app/blog_controller.rb`. (${workspaceFolder} is `/Users/<my user>/work/blog`)

I have tried a lot of combinations of `localfs` and `localfsMap` but nothing works.  It still gets the wrong path.  Likewise I am unable to successfully set a breakpoint in vscode because it also tries to breakpoint by file_path and line_number and the file_path is wrong.

The launch.json is:
```
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "type": "rdbg",
      "name": "Attach with rdbg",
      "request": "attach",
      "debugPort": "9876",
      "localfs": true,
      "localfsMap": "/app:${workspaceFolder}",
      "showProtocolLog": true
    }
  ]
}
```
(I have tried it without the `"localfs": true,` line as well)

Why is localfsMap not working?  Is there anything I can do to help diagnose the issue?

**Comment by ono-max** [comment]
Thank you for reporting.
Could you show us the sample program to reproduce this problem?

**Comment by ghouston** [comment]
@ono-max i dont have a readily available sample to produce the problem. its happening in a proprietary cloud environment.  is there a way to debug the issue or provide logs that would help?

**Comment by ono-max** [comment]
I want to check if the problem occurs only in the cloud environment first. Could you check if the problem occurs in the docker-compose environment? The following environment is an example.

https://github.com/Kounotori-ssbm/vscode-rdbg-issue250-reproduction

**Comment by ghouston** [comment]
@ono-max I can run the docker dev environment https://github.com/Kounotori-ssbm/vscode-rdbg-issue250-reproduction and get it to successfully debug from vscode.

However, I notice that vscode-rdbg-issue250-reproduction isn't using the localfsMap.  So it can't reproduce the error I'm having with localfsMap.

Also I see that vscode-rdbg-issue250-reproduction is connecting rdbg by unix domain socket.  While in the case I'm having trouble with, rdbg is connecting over a tcp/ip port.

Another difference is the extension is installed on the remote (inside vscode-rdbg-issue250-reproduction).  While in my case, vscode is not attaching to a remote container or tunnel (via microsoft extensions).  There is no vscode server in the cloud environment where rails is running.  In my cloud its just rails with the debug gem and a port mapped from my local to rdbg's port on the cloud.  Which is why I can successfully debug from my local command-line using `rdbg -A`. In my vscode, I can see the debugger is talking with my cloud environment. VS Code debugger is stopping on a 'binding.break' in my code when use the launch.json with the debugPort specified. Its just confused about where the file is located on my local path verses the server path.

**Comment by benedictfischer09** [comment]
Removing this conflicting setting should resolve the issue for you
```
"localfs": true
```

**Comment by ghouston** [comment]
Thank you @benedictfischer09, I can confirm the `"localfs": true` setting was the problem.  When I removed it, the debugger worked correctly!

cc: @ono-max
