### ISSUE TITLE
This is great!

### ISSUE THREAD

**Issue by ddnexus** [ruby/vscode-rdbg#3]
This thing is very functional, easy to use and efficient! Thank you for your great work!

I love the possibility to debug anything on the fly by entering its command (e.g. `bundle exec rake test` ), however as soon as I add a config, when I use `F5` it just runs it and doesn't ask for input anymore. 

That is very useful for quick entries, without having to enter a new config. How can I trigger it even when some launch configuration is set?

**Comment by ko1** [comment]
your question is,  how to change default value in a dialog?

**Comment by ddnexus** [comment]
Not sure there is any default to change in any dialog. 

If I add a launch configuration, I don't find any way to get the default prompt that ask me for entering a command. If there is a launch configuration in the `launch.json`, `F5` will not show me the prompt at all. It will just run the configuration, no prompt.

**Comment by ko1** [comment]
Could you try to change `askParameters` configuration? https://github.com/ruby/vscode-rdbg#configuration

**Comment by ddnexus** [comment]
I tried a few days ago and it didn't work. Just to be sure, could you post
a complete example that is supposed to work here? Thanks.

**Comment by ddnexus** [comment]
I think I had some sort of misconfiguration somewhere, maybe the residual of another debug that I was using earlier or some mess in a docker volume. I delete the old volume, rebuild everything from scratch and.... tah dah!!!! 
Your debugger works perfectly!!! 
Sorry for the noise, and thank you for your great work!
