### ISSUE TITLE
Publish `vscode-rdbg` in `open vsx`

### ISSUE THREAD

**Issue by tanmoysrt** [ruby/vscode-rdbg#317]
According to the latest Microsoft Terms & Policy, VSCodium, Theia IDE, which is used by many remote development platforms like Gitpod, cant use the VSCode marketplace to fetch the extensions.

Alternatively, [Open VSX Registry](https://open-vsx.org/) offers to use the extensions without licensing issues. 

I request to publish this extension in the [Open VSX Registry](https://open-vsx.org/) registry.

It's simple to publish in open-vsix and you can get a [guide here](https://www.gitpod.io/blog/open-vsx#publishing)

**Comment by tanmoysrt** [comment]
@ono-max what do you think about this ?

**Comment by ono-max** [comment]
Thank you for your proposals, and I already created a PR https://github.com/ruby/vscode-rdbg/pull/109 tro support open vsx. However, we can't merge it now because we don't have a LICENSE yet.

**Comment by tanmoysrt** [comment]
@ono-max oh, got it.

**Comment by ono-max** [comment]
Could you join the conversation in https://github.com/ruby/vscode-rdbg/issues/5? It may be push to supporting open vsx.
