### ISSUE TITLE
Debug console output from multiple debugging processes always appears in the currently active debug console

### ISSUE THREAD

**Issue by hoylemd** [ruby/vscode-rdbg#318]
I've found that when running multiple debugger processes at the same time, the console output from all processes ends up in whatever debug console window I happen to have open.

I set up a simple demo repository that can be used to demonstrate the issue fairly easily:

https://github.com/hoylemd/vscode-ruby-console-debug-demo

How to:

- clone that repo
- open up a workspace in the clones repo directory
- install the vscode-rdbg extension if it's not already active
- Run the 'hickory(rdbg)' debug configuration
- immediately also run the 'dickory(rdbg)' debug configuration

You'll see the output from both processes appear in whatever debug console window you have open, they're prefixed with their names so you can tell which is which.

e.g.

![Screen Shot 2023-07-21 at 18 49 14](https://github.com/ruby/vscode-rdbg/assets/569403/7f9b03e5-44a4-4c67-bd97-20ea174b88e3)

The same issue appears in the `ruby_lsp` extension, I'll log a similar issue under that and link it here: https://github.com/Shopify/vscode-ruby-lsp/issues/714

@st0012 on the Ruby DX slack server had this to say about it, which may be helpful in fixing the issue:

> Yeah I think it’s probably because the extension always passes the [active debug console](https://github.com/ruby/vscode-rdbg/blob/27963ffa27bbd283e322fe478bbd4953b576aece/src/extension.ts#L858C9-L858C21) to functions that [run debuggee processes](https://github.com/ruby/vscode-rdbg/blob/27963ffa27bbd283e322fe478bbd4953b576aece/src/extension.ts#L940-L979).

**Comment by ko1** [comment]
duplicate with https://github.com/ruby/vscode-rdbg/issues/111
(please reopen if it's wrong)
