### ISSUE TITLE
Does the cwd option work in an attach configuration?

### ISSUE THREAD

**Issue by LarryNorth** [ruby/vscode-rdbg#32]
It seems that the cwd option in an attach launch configuration has no effect. I use docker-compose to run `rdbg --open --port ...` in a Docker container. When I run the corresponding attach launch configuration, rdbg tries to start the script in a folder that matches the vscode project folder on the host instead of the container's folder on which the project folder is mounted. Setting cwd to the container's folder has no effect. If the project's folder is mounted on an identically named folder (full path) in the container, it all works.

**Comment by ko1** [comment]
with vscode-rdbg 0.0.9?

**Comment by ko1** [comment]
* `cwd` option is not supported on `attach` because `cwd` option is for "how to launch the debugger/debuggee".
* Using TCP/IP, all source access is by "Source" request and it doesn't open the source code in docker's filesystem. So I think you can see, but can not edit it. Correct?

> When I run the corresponding attach launch configuration, rdbg tries to start the script in a folder that matches the vscode project folder on the host instead of the container's folder on which the project folder is mounted

"attach" doesn't run the debugger, but attach to already running Ruby process. So "rdbg tries to start the script" is not correct.

**Comment by LarryNorth** [comment]
Yes, with vscode-rdbg 0.0.9. The debug gem version is 1.5.0.

**Comment by ko1** [comment]
> Something like the remoteWorkspaceRoot option that ruby-debug-ide uses in its vscode launch configuration may solve this problem

Yes. Same as https://github.com/ruby/debug/issues/463

**Comment by LarryNorth** [comment]
Yes. I my case the Docker container is [ruby/debug#463](https://github.com/ruby/debug/issues/463)'s remote development machine. It seems that the `rdbg` vscode attach launch configuration would include the remote host, the remote port, and the remote source tree root.  Here's an example from `ruby-debug-ide`:
```
        {
            "name": "Listen for rdebug-ide",
            "type": "Ruby",
            "request": "attach",
            "remoteHost": "127.0.0.1",
            "remotePort": "1234",
            "remoteWorkspaceRoot": "${workspaceRoot}"
        }
```
I am able to use `rdbg` now by bind mounting the local system's source tree root to the same location in the Docker container. (There's also some Docker port mapping involved.) There's no need for `watchman` or `rsync` because the local source tree's files and the those in the Docker container are the same physical files.  `ruby-debug-ide`'s `remoteWorkspaceRoot` option allows the source tree root to be mounted anywhere in the Docker container.

**Comment by firien** [comment]
From [vscode #120307](https://github.com/microsoft/vscode/issues/120307#issuecomment-812190844) I hacked together a demo of remoteWorkspaceRoot/remoteRoot from existing `RdbgDebugAdapterTrackerFactory` - translating source paths from VSCode <=> DA

[remote-root-demo](https://github.com/firien/vscode-rdbg/tree/remote-root-demo)

You can test this locally with a simple ruby file. Make 2 copies of file, they should be named the same but live in different directories; like:

* `/path/to/remote-demo/demo.rb`
* `/path/to/anywhere-else/demo.rb `

From  `/path/to/remote-demo` run `rdbg demo.rb --open --port 12345`.
Open `/path/to/anywhere-else` in vscode and launch debug with attach. Please note new `remoteRoot`, and `localfs` must be true

```
{
  "type": "rdbg",
  "name": "Attach with rdbg",
  "request": "attach",
  "debugPort": "12345",
  "localfs": true,
  "remoteRoot": "/path/to/remote-demo"
}
```

----

I have also installed this on remote vscode and verified it "works" within a rails Docker container. There are definitely issues with docker volumes not mapped locally.

----

1 bug I found locally was if you still have breakpoints set in vscode and detach - it will crash `rdbg`

----

This is by no means a finished product - just the bare minimum to get this working in my remote docker environment.

**Comment by firien** [comment]
> 1 bug I found locally was if you still have breakpoints set in vscode and detach - it will crash `rdbg`

This also crashes with the published `vscode-rdbg`, so maybe it's related to this issue in debug itself - https://github.com/ruby/debug/issues/622

**Comment by firien** [comment]
> I have also installed this on remote vscode and verified it "works" within a rails Docker container. There are definitely issues with docker volumes not mapped locally.

https://github.com/ruby/vscode-rdbg/issues/29#issuecomment-1101666164

I cleaned up the code a lot and enabled multiple remote directory mappings in https://github.com/firien/vscode-rdbg/tree/multi-remote-root

**Comment by firien** [comment]
I can get `localfsMap` to load the correct local file - but it appears that setting breakpoints will register the local file, and not the remote file that is actually running in code.
https://github.com/ruby/debug/blob/bea4bf52efad4e7f79c0e42bc11d131fa67ec8a7/lib/debug/server_dap.rb#L263

I think you need to map the local path (from vscode breakpoint UI) back to the remote path; a reverse of the current `local_fs_map_path` method
```ruby
def self.remote_fs_map_path path
  case @local_fs_map
  when nil
    false
  when true
    path
  else # Array
    @local_fs_map.each do |(remote_path_prefix, local_path_prefix)|
      if path.start_with? local_path_prefix
        return path.sub(local_path_prefix){ remote_path_prefix }
      end
    end

    nil
  end
end
```

**Comment by ko1** [comment]
Thank you, that's right. Maybe I can overlook so please tell me if you find issues.
