### ISSUE TITLE
debugPort: "0" does not work

### ISSUE THREAD

**Issue by jabamaus** [ruby/vscode-rdbg#33]
There appears to be an off by one error in the port number. See attached screenshot
![vscode-rdbg-debugport_error](https://user-images.githubusercontent.com/49597106/161254226-2eb60437-b870-428f-9872-1b14314cd500.PNG)

Environment:

Windows 10
Vscode 1.66
vscode-rdbg 0.0.10
debug gem 1.5.0
ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [x64-mingw-ucrt]
.

**Comment by ko1** [comment]
I see. `rdbg --util=gen-portpath` doesn't work on Windows.
I'll fix it.
