### ISSUE TITLE
VSCode integration connect ENOENT message when debugging

### ISSUE THREAD

**Issue by raymart-evangelista** [ruby/vscode-rdbg#34]
I am trying to use debug with VSCode and this message pops up: 
![image](https://user-images.githubusercontent.com/100163647/162289580-0933507f-6842-4654-813b-8efaa1c9f699.png)

The launch.json file is currently untouched.

I can provide more information if necessary.

**Comment by ko1** [comment]
Sorry for late.
Could you give me a step-by-step reproduce process?

**Comment by ko1** [comment]
Please reopen if you have any more info.
