### ISSUE TITLE
Debugging in VS Code Remote (WSL2)

### ISSUE THREAD

**Issue by shayani** [ruby/vscode-rdbg#345]
I'm configuring VSCode to debug my Rails app. I'm running the latest version os VSCode, Ruby 3.2.2 and WSL2 (debian).

I created a standard `launch.json` file with this configuration:
```
{
  "type": "rdbg",
  "name": "Attach with rdbg",
  "request": "attach"
}
```

and I'm able to start my Rails app with 
```
rdbg -n -O 12345 -c -- bundle exec rails server
```

If I open a new terminal and run `rdbg -A`, I can connect to the debugger, but when I try to start the debugger on VSCode with this configuration, nothing happens. VSCode keeps trying to start the debugger without success.

What am I missing?

Thanks

**Comment by feliperaul** [comment]
I'm on a mac, so I don't know if it'll work for you, but I managed to connect inside Vs Code by using:

`RUBY_DEBUG_OPEN=true bundle exec rails s`

As I'm also using YJIT, the entire command is:

`RUBY_YJIT_ENABLE=1 RUBY_DEBUG_OPEN=true bundle exec rails s`

Just add that line to your Procfile (I use `overmind`):

`rails: RUBY_YJIT_ENABLE=1 RUBY_DEBUG_OPEN=true bundle exec rails s`

**Comment by dj-sf** [comment]
Im having this same problem too... did any of this work?

**Comment by shayani** [comment]
Indeed, it worked. When I start `RUBY_DEBUG_OPEN=true bundle exec rails server`, VSCode can now connect to the debugger, even inside WSL2.
