### ISSUE TITLE
Implement global variables in variable view

### ISSUE THREAD

**Issue by jabamaus** [ruby/vscode-rdbg#35]
They currently say "Not implemented yet...". I would really like to see my global variables.

**Comment by ko1** [comment]
Okay.

**Comment by ko1** [comment]
The reason I skipped this feature because it shows unclear errors and I couldn't debug it :p I'll revisit it again.

**Comment by jabamaus** [comment]
Brilliant. Thank you!

**Comment by ko1** [comment]
already fixed.
