### ISSUE TITLE
cannot find a program to debug

### ISSUE THREAD

**Issue by pablox70** [ruby/vscode-rdbg#367]
When I run this configuration on a ruby file (Ruby-LSP is installed) I get the error in VS Code (v 1.83.1)
"Cannot find a program to debug."

This is the configuration
    "configurations": [      
      {
        "type": "rdbg",
        "name": "Debug current file",
        "request": "launch",
        "script": "",
        "askParameters": true
      },

**Comment by tobytang1987** [comment]
This error happens when "script" is empty.

**Comment by pablox70** [comment]
Thanks - it's working now.

**Comment by merof-code** [comment]
What should we put there? A random command?

**Comment by ko1** [comment]
`"script": 'script_name_which_you_want_to_run.rb'`
