### ISSUE TITLE
set/unset breakpoints on running debug doesn't seem to work

### ISSUE THREAD

**Issue by nancheal** [ruby/vscode-rdbg#49]
ruby/debug 1.6.0
vscode-rdebug 0.0.11
rails app in docker

launch.json
`
{
          "type": "rdbg",
          "name": "Attach rdbg",
          "request": "attach",
          "debugPort": "0.0.0.0:12345",
          "localfs": true
}
`

Similar to previous question:
https://github.com/ruby/vscode-rdbg/issues/17
https://github.com/ruby/debug/issues/519

for example, i unset breakpoint on gitlab_projects_controller.rb(the only bp is on decompressed_archive_size_validator.rb), but it still break on gitlab_projects_controller.rb
![image](https://user-images.githubusercontent.com/12165569/178440644-f0555fc2-15f9-401d-8580-ae06bc2b93fc.png)
![image](https://user-images.githubusercontent.com/12165569/178440718-a7c1930d-d882-45fa-82e4-1582a10627b9.png)

It feels like a bug in vscode rdbg rather than a bug in debug.gem
Repeatedly set/unset many times may unset this breakpoint

**Comment by ko1** [comment]
Thank you for the report.

1. Could you make a repro small steps I can try?
2. Could you share me the protocol log? (`showProtocolLog: true` in launch.json)

Maybe it is a bug within DAP handling part in debug.gem.

**Comment by nancheal** [comment]
Thank you for your reply, I am debugging gitlab in docker (Uploading any non-gitlab export project can trigger breakpoints)
![image](https://user-images.githubusercontent.com/12165569/179176978-5b499224-0d00-4ede-83e3-a4c425927553.png)
 
debug command
`rdbg --open --port 12345 --host 0.0.0.0 -c bin/rails s`

I tried to enable showProtocolLog in launch.json, set breakpoint in the same position, and then unset breakpoint, the following is the log, Looking at the log doesn't seem like a bug
`[VSCode->DA] {"command":"setBreakpoints","arguments":{"source":{"name":"gitlab_projects_controller.rb","path":"/home/gdk/gitlab-development-kit/gitlab/app/controllers/import/gitlab_projects_controller.rb"},"lines":[17],"breakpoints":[{"line":17}],"sourceModified":false},"type":"request","seq":28}
[DA->VSCode] {"type":"response","command":"setBreakpoints","request_seq":28,"success":true,"message":"Success","body":{"breakpoints":[{"verified":true}]},"seq":25092}
[VSCode->DA] {"command":"setBreakpoints","arguments":{"source":{"name":"gitlab_projects_controller.rb","path":"/home/gdk/gitlab-development-kit/gitlab/app/controllers/import/gitlab_projects_controller.rb"},"lines":[],"breakpoints":[],"sourceModified":false},"type":"request","seq":29}
[DA->VSCode] {"type":"response","command":"setBreakpoints","request_seq":29,"success":true,"message":"Success","body":{"breakpoints":[]},"seq":25092}`

**Comment by ko1** [comment]
So you mean

> [VSCode->DA] {"command":"setBreakpoints","arguments":{"source":{"name":"gitlab_projects_controller.rb","path":"/home/gdk/gitlab-development-kit/gitlab/app/controllers/import/gitlab_projects_controller.rb"},"lines":[],"breakpoints":[],"sourceModified":false},"type":"request","seq":29}

removes the BPs from `gitlab_projects_controller.rb`, but it still remaining.

https://github.com/ruby/debug/blob/master/lib/debug/server_dap.rb#L300
This line clears the BPs in the given path.
Could you put `pp @bps` intohttps://github.com/ruby/debug/blob/master/lib/debug/session.rb#L1373 (just after removing the BPs)?

**Comment by nancheal** [comment]
Is pp @bps right here?
![image](https://user-images.githubusercontent.com/12165569/179184617-e0c9bf86-c5dd-4d5e-b265-30feb84a6e14.png)

Whether the output of set or unset is {}
![image](https://user-images.githubusercontent.com/12165569/179184310-d57d6a28-6697-4d48-886c-88cf7e77b85b.png)

**Comment by nancheal** [comment]
i pp @bps here
![image](https://user-images.githubusercontent.com/12165569/179185657-5a3b592f-da19-4ac0-a8a8-96305e388254.png)

set/unset output is {}
![3e79edcd951b8624983f66481c4b23a](https://user-images.githubusercontent.com/12165569/179185803-b16149ef-f16d-48e4-9123-754b293e4977.png)

**Comment by nancheal** [comment]
I now use binding.break to set a breakpoint, and I found that the breakpoint must take effect every time the file is changed and then save the source code file, maybe this is the bug?

**Comment by ko1** [comment]
> I now use binding.break to set a breakpoint, and I found that the breakpoint must take effect every time the file is changed and then save the source code file, maybe this is the bug?

Sorry I couldn't understand your points.

(1) You write a line `binding.break` on the file X.rb
(2) Loaded X.rb with debugger
(3) Modify X.rb with `binding.break` line (B)
(4) the breakpoint (B) is effective after realoding X.rb

I think it is correct. or do I missing?

**Comment by nancheal** [comment]
I thought about it, you are right, the mechanism of modifying the source code to set a breakpoint is different from that of setting a breakpoint through vscode, ignore it

**Comment by ko1** [comment]
Ok I close this issue (sorry for late response) and please make new issue if you find another issue.
