### ISSUE TITLE
Debugger seems to disconnect instantly

### ISSUE THREAD

**Issue by dgaus** [ruby/vscode-rdbg#51]
Hi, I'm trying to switch to vscode and found this debugger recommended. However I am not able to make it work -- while it starts, vscode seems to connect and disconnect immediately, after which I'm unable to set breakpoints.

```
cd /Users/diego/code/portal/backend
rdbg --command --open --stop-at-load --sock-path=/var/folders/gt/hx3zr_715_j2bfp04xk8lvjr0000gn/T/ruby-debug-sock-501/ruby-debug-diego-30431 -- rails server 

# diego @ kepler in ~/code/portal/backend [12:35:08] 
$ cd /Users/diego/code/portal/backend
chruby: unknown Ruby: 3.0.4

# diego @ kepler in ~/code/portal/backend [12:35:08] 
$ rdbg --command --open --stop-at-load --sock-path=/var/folders/gt/hx3zr_715_j2bfp04xk8lvjr0000gn/T/ruby-debug-sock-501/ruby-debug-diego-30431 -- rails server 
DEBUGGER: Debugger can attach via UNIX domain socket (/var/folders/gt/hx3zr_715_j2bfp04xk8lvjr0000gn/T/ruby-debug-sock-501/ruby-debug-diego-30431)
DEBUGGER: wait for debugger connection...
DEBUGGER: Connected.
=> Booting Puma
=> Rails 6.1.6.1 application starting in development 
=> Run `bin/rails server --help` for more startup options
[30596] Puma starting in cluster mode...
[30596] * Puma version: 5.6.4 (ruby 3.0.4-p208) ("Birdie's Version")
[30596] *  Min threads: 1
[30596] *  Max threads: 1
[30596] *  Environment: development
[30596] *   Master PID: 30596
[30596] *      Workers: 3
[30596] *     Restarts: (✔) hot (✖) phased
[30596] * Preloading application
[30596] * Listening on http://127.0.0.1:3000
[30596] * Listening on http://[::1]:3000
[30596] Use Ctrl-C to stop
[30596] - Worker 0 (PID: 30667) booted in 0.0s, phase: 0
[30596] - Worker 1 (PID: 30668) booted in 0.0s, phase: 0
[30596] - Worker 2 (PID: 30669) booted in 0.0s, phase: 0
```

I tried manually starting the rails server from a console using `rdbg --open --command bundle exec rails s`, then connecting from vscode using `rdbg attach`, at which point I get a breakpoint in the first line, but after I click continue it disconnects as well. Am I missing anything trivial? Thanks in advance!

**Comment by gwillcox-r7** [comment]
Hmm so this worked for me when I was testing things out, not sure if this is just me though but thought I'd share here: 

Launch.json:
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "rdbg",
            "name": "Debug current file with rdbg",
            "request": "launch",
            "script": "${cwd}/msfconsole",
            "args": [],
            "askParameters": true,
        },
        {
            "type": "rdbg",
            "name": "Attach with rdbg",
            "request": "attach",
            "debugPort": "34334"
        }
    ]
}
```

Then in the terminal of VSCode I did this:

```
rdbg --open --port=34334 -- msfconsole 
```

And finally I ran the `Attach with rdbg` action. This worked fine and I could hit breakpoints multiple times with Ruby 3.0.2.

Unfortunately still haven't figured out a way to get this working with the "Debug current file with rdbg". I imagine an option to change the launch parameters might be needed in order to get that to work.

**Comment by enigmatic-maelstrom** [comment]
I am having this exact same issue with Ruby 3.1.2 and the Rails example blog project. The issue for me at least appears to happen with attaching to a remote debugging instance (in my case from within a container).

I've been starting the rails server thusly: `rdbg -O --nonstop --host 0.0.0.0 --port 1234 -c -- rails s -b 0.0.0.0`

From within code I have been using the following launch.json:
`
{
    "type": "rdbg",
    "name": "Attach with rdbg (tcp 1234)",
    "request": "attach",
    "debugPort": "localhost:1234",
    "localfsMap": "/opt/blog:${workspaceFolder}"
}
`

The experience is seemingly identical to OP. Regardless if I wait for the debugger or not, the ending is roughly the same in that the code debugger disconnects. What is more uniquely interesting however is when waiting for the debugger before resuming the process (in this case a Rails server), it does break at the first line of the initial bundle/bin/rails file, just like OP. There is NO breakpoint set here, and upon continuing the debugger disconnects.

From what little debug output I could gain I have the following error noted:

`[Start session]
{"_debugServiceProxy":{},"_id":"35ef5167-975f-427c-a7d0-c87690ad022e","_type":"rdbg","_name":"Attach with rdbg","_workspaceFolder":{"uri":{"$mid":1,"fsPath":"/Users/username/Desktop/blog","external":"file:///Users/username/Desktop/blog","path":"/Users/username/Desktop/blog","scheme":"file"},"name":"blog","index":0},"_configuration":{"type":"rdbg","name":"Attach with rdbg","request":"attach","debugPort":"1234","__configurationTarget":6}}
[Error on seession]
Error: connection closed
e: {}`

This has become incredibly frustrating as I'd very much like to move away from ruby-debug-ide, however that is at least working. At the very least some additional logging to troubleshoot with would be very helpful. Any thoughts?

**Comment by ko1** [comment]
same with `bin/rails` for launching the server?

**Comment by dcohenb** [comment]
Having the same issue,

My setup:
Ruby 3.1.2
debug gem 1.6.2
rails 7.0.4

Running in a docker container, startup command:
``rdbg --open --nonstop --port=9220 -c -- bin/rails s -p 3000 -b 0.0.0.0``

Upon start up I get:
`DEBUGGER: Debugger can attach via TCP/IP (127.0.0.1:9220)`

docker port is exposed

My launch.json configuration:
```
{
            "type": "rdbg",
            "name": "library",
            "request": "attach",
            "debugPort": "9220",
            "localfsMap": "/usr/app:${workspaceFolder}\\library"
}
```

vscode launch error:
```
[Start session]
{"_debugServiceProxy":{},"_id":"f26bd574-7d9e-437a-9e2c-0c9db90e0e9a","_type":"rdbg","_name":"library","_workspaceFolder":{"uri":{"$mid":1,"fsPath":"c:\\Users\\User\\Projects\\myproject","_sep":1,"external":"file:///c%3A/Users/User/Projects/myproject","path":"/c:/Users/User/Projects/myproject","scheme":"file"},"name":"myproject","index":0},"_configuration":{"type":"rdbg","name":"api","request":"attach","debugPort":"9220","localfsMap":"/usr/app:C:\\Users\\User\\Projects\\myproject\\api","__configurationTarget":6}}
[Error on seession]
Error: connection closed
e: {}
```


Some things I have tried:
- with / without `--nonstop` flag
- starting rails with `bundle exec rails server`
- downgrading to ruby 3.0.4
- upgrading to ruby 3.2.0
- downgrading to debug gem 1.5.0
- many other things I don't remember, I spent a good couple of days on this already.

**Comment by dcohenb** [comment]
Found my issue
In the docker start command you need to bind the rdbg process to 0.0.0.0

`rdbg --open --port=9220 --host=0.0.0.0 --nonstop -c -- bin/rails s -p 3000 -b 0.0.0.0`

this solved it for me at least

**Comment by ko1** [comment]
Ah, I see. I close it and please ping me if I misunderstood.
