### ISSUE TITLE
Unable to set breakpoints in slim or haml files without "Allow Breakpoints Everywhere" enabled

### ISSUE THREAD

**Issue by rbclark** [ruby/vscode-rdbg#54]
First off, this extension is great and I've been really enjoying using it on all my Rails projects. 

I've just run into one small problem, I am unable to place breakpoints in slim or haml files without enabling "Allow Breakpoints Everywhere" in my vscode settings. Debugging works properly once "Allow Breakpoints Everywhere" is set, it seems there is just a misconfiguration either in this package or in the slim & haml packages which is stopping this from working. From my research it looks like the [same thing was happening with vscode-cpptools](https://github.com/microsoft/vscode-cpptools/pull/9484) and they fixed it by adding "rust" to their language list.

**Comment by ko1** [comment]
It is first time to see `"Allow Breakpoints Everywhere"` option.
Ah, I see so we need to add languages "slim" "haml" .... maybe on https://github.com/ruby/vscode-rdbg/blob/master/package.json#L43 ?
Do you know other languages we should support on?

**Comment by rbclark** [comment]
@ko1 Yep that seemed to fix it! I put in a PR that adds slim and haml, I can't think of any other extension types that should be supported.

**Comment by ko1** [comment]
`.erb`?
