### ISSUE TITLE
Launch and attach to rails console?

### ISSUE THREAD

**Issue by DaveSanders** [ruby/vscode-rdbg#63]
I need to do some interactive debugging of portions of background tasks and would like to be able to launch `rails console` with the debugger and attach VS Code to it.

So far, I have the launch task below.  The console launches fine, shows that a debugger can attach, etc.  VS Code attempts to attach to the debugger, but then closes the tool box and acts as if the connection was closed.  I'm not seeing any errors anywhere, including the dev console.

Is it just not possible to connect the debugger this way?  I also tried launching the console from the command line and then attach after the fact, but that gives me "ECONNREFUSED" errors - possibly because I'm running VSC on Windows, but my dev environment is under WSL2.  

Hoping maybe someone else has done this and can point me in the right direction.

```
    {
      "type": "rdbg",
      "name": "Debug Console",
      "request": "launch",
      "command": "rails",
      "script": "c",
      "args": [],
      "askParameters": false
    }
```

**Comment by ko1** [comment]
do you want to attach to `rails console` process or "background tasks"?

**Comment by DaveSanders** [comment]
I'm wanting to fire up a Rails console session with a debugger attached, then go into Code, set a breakpoint, and when I call a method that has a breakpoint in it, have Code and console pause and let me inspect what's going on.

**Comment by firien** [comment]
```json
{
  "type": "rdbg",
  "name": "Launch Rails Console",
  "request": "launch",
  "command": "bin/rails",
  "args": ["--", "--noautocomplete"],
  "script": "console",
  "useBundler": false,
  "rdbgPath": "bin/rdbg"
}
```

I launch rails console with above configuration without issue. Note that I am not using bundler and using the rdbg binstub.

RUBY: 3.0.4
DEBUG_GEM: 1.6.2

-----

If I switch to args below, then I also cannot connect, although I get no specific errors. Just `Error: connection closed` in rdbg Output panel.

```json
"command": "rails",
"script": "c",
"args": []
```

**Comment by DaveSanders** [comment]
@firien perfect, thank you for the proper incantation!

For anyone else finding this later: I did have to change rdbgPath since I'm using asdf, but that was easily found with a `which rdbg` and updating the task.

Thanks again!
