### ISSUE TITLE
Support env for the attach command

### ISSUE THREAD

**Issue by renatolond** [ruby/vscode-rdbg#81]
Hi! Thanks for your work!

For now, it seems that the attach command does not accept the `env` variable
![image](https://user-images.githubusercontent.com/173791/200601723-9a6a5013-18bb-43c0-94e9-0379cded3ee5.png)

I would like to be able to pass the `RUBY_DEBUG_SOCK_DIR` to the attach command, I can do it from my terminal, but not from the extension at the moment.

Would this be possible?

**Comment by ko1** [comment]
Ah, I see. It should be fixed.
