### ISSUE TITLE
rdbg in Gemfile not working

### ISSUE THREAD

**Issue by rongcuid** [ruby/vscode-rdbg#9]
Even with setting "Use Bundler" set, `debug` installed with Gemfile causes Command Not Found error.

**Comment by ko1** [comment]
Did you install debug gem?

**Comment by rongcuid** [comment]
No. I confirm that when `debug` is installed, use bundler works. However, when `debug` itself is a Gemfile dependency, this extension would not work.

**Comment by ko1** [comment]
Sorry, I can't understand your situation.
Could you explain more with the code examples?

**Comment by rongcuid** [comment]
For instance, I have 

```
  spec.add_development_dependency 'debug', '~> 1.0'
```

in my `gemspec`. However, `deubg` gem is _not_ installed system wide. Thus when I run `bundler`, `rdbg` is installed locally in `vendor`. In this case, I need to start `rdbg` using the command `bundle exec rdbg`.

**Comment by ko1** [comment]
Ah, I see. How to solve this issue...?
Current extension expects that rdbg (debug.gem) is installed in `$PATH`.

**Comment by ko1** [comment]
You can specify `rdbgPath` configuration for `rdbg` path, and specify `bundle exec rdbg` will help?

**Comment by rongcuid** [comment]
I don't see this config. Do I need to edit config JSON?

**Comment by ko1** [comment]
Yes. https://github.com/ruby/vscode-rdbg#configuration

**Comment by rongcuid** [comment]
It does not work:

```
Error: exit code is 10
Make sure to install rdbg command (`gem install debug`).
If you are using bundler, write `gem 'debug'` in your Gemfile.
```

Launch.json:

```
        {
            "type": "rdbg",
            "name": "Debug current file with rdbg",
            "request": "launch",
            "script": "${file}",
            "args": [],
            "askParameters": true,
            "rdbgPath": "bundle exec rdbg"
        }
```

**Comment by kjg** [comment]
I think this is because 

https://github.com/ruby/vscode-rdbg/blob/636388aa96a66fa976afa3a1bc62d370592c682a/src/extension.ts#L193-L201

Is not happening in the context of ${workspaceFolder}

I get the same error code when I run the command outside my workspaceFolder

```bash
-- $ bundle exec rdbg --util=gen-sockpath
Could not locate Gemfile or .bundle/ directory

-- $ echo $?
10
```

I was able to work around this by setting `"rdbgPath": "cd ${workspaceFolder} && bundle exec rdbg",`

This seems a tad dangerous that the extension will just execute anything in placed in rdbgPath, but this workaround seems to work for now.

**Comment by ko1** [comment]
Thak you @kjg

@rongcuid is your issue out of `${workspaceFolder}` ?

**Comment by rongcuid** [comment]
> @rongcuid is your issue out of `${workspaceFolder}` ?

What do you mean by out of workspace? My bundler is set up at the workspace root, but rdbg would not launch in any folder by using the extension. I have not tried the workaround yet.

**Comment by camiloforero** [comment]
After hitting my head for a while with this program I just called it in, ran `gem install debug` and called it a day.
Got a weird "EPIPE" error with the `"rdbgPath": "cd ${workspaceFolder} && bundle exec rdbg"` attempt

**Comment by ko1** [comment]
Sorry for absent, maybe you forget the situation (and I did) , but my last question may be "does your issue solve with configuration: `"rdbgPath": "cd ${workspaceFolder} && bundle exec rdbg"`"?

**Comment by ChristianClassen** [comment]
@ko1 Thanks for this hint. I couldn't start rdbg with Bundler either, but your command works!

It starts the Rails server, attaches the debugger and breakpoints are hit and you can inspect the variables.

This launch.json works for me debugging with Rails 7:

` {
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "type": "rdbg",
      "name": "Debug Rails with rdbg",
      "rdbgPath": "bundle exec rdbg",
      "request": "launch",
      "cwd": "${workspaceFolder}",
      "command": "${workspaceFolder}/bin/rails",
      "script": "server"
    }
  ]
}`

**Comment by ko1** [comment]
Thank you for information. Please reopen (or renew) the ticket if you have inconvenient.
